language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "jython"

# jython hacks
before_install:
  - export JYTHON_URL='http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar?r=http%3A%2F%2Fwww.jython.org%2Fdownloads.html&ts=1338089844&use_mirror=iweb'
  - if [ "$TRAVIS_PYTHON_VERSION" == "jython" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "jython" ]; then $HOME/jython/bin/jython $HOME/virtualenv/bin/pip install virtualenv; fi

before_script: if [ "$TRAVIS_PYTHON_VERSION" == "jython" ]; then export PATH=$HOME/jython:$PATH; export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi


# install dependencies
install:
  - pip install -r test-requirements.txt --use-mirrors

# run tests
script: $PYTHON_EXE setup.py test

# Notify maintainers
notifications:
 recipients:
   - bugs+paver@gmail.com
 email:
   on_success: change
   on_failure: always
